name: json2builtvalue
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: rafal.wachol <email@example.com>

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  test: "^1.0.0"
  code_builder: ^4.4.0
  recase: "^4.1.0"
  tuple: ^2.0.1
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
